from typing import Protocol, Optional

class Sensor(Protocol):
    """
    Minimal interface all sensors should implement.
    """
    name: str

    def initialize(self) -> None: ...
    def start(self) -> None: ...
    def read(self): ...
    def stop(self) -> None: ...
    def cleanup(self) -> None: ...
